version: "3.9"

services:
  api:
    build: .
    working_dir: /home/app
    ports:
      - 8080:${PORT}
    env_file:
      - .env
    volumes:
      - ./:/home/app
  db:
    container_name: example-go-graphql-mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sample
      MYSQL_DATABASE: graphql_go_example
    ports:
      - 3308:3306
